
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '6\x9e\x95\xab\xcf:\xc5\x8b\xa9X\x8fp\xda2\xa6\xbc'
    
_lr_action_items = {'LBRACE':([6,],[8,]),'NAME':([6,8,11,14,20,21,22,23,26,],[17,17,17,17,17,17,17,17,17,]),'KEYWORD':([0,1,4,5,7,],[-1,2,-4,-2,-3,]),'JOINTVAR':([6,8,11,14,20,21,22,23,26,],[9,9,9,9,9,9,9,9,9,]),')':([9,13,15,16,17,24,25,28,29,30,31,],[-20,-17,-16,-18,-19,-15,32,-12,-11,-13,-14,]),'(':([6,8,26,],[14,14,14,]),'+':([9,10,13,15,16,17,24,25,28,29,30,31,],[-20,21,-17,-16,-18,-19,-15,21,-12,-11,-13,-14,]),'NEWLINE':([0,1,3,4,5,7,9,10,12,13,15,16,17,24,27,28,29,30,31,32,],[-1,4,7,-4,-2,-3,-20,-9,-5,-17,-16,-18,-19,-15,-6,-12,-11,-13,-14,-10,]),'-':([6,8,9,10,11,13,14,15,16,17,20,21,22,23,24,25,26,28,29,30,31,],[11,11,-20,20,11,-17,11,-16,-18,-19,11,11,11,11,-15,20,11,-12,-11,-13,-14,]),'*':([9,10,13,15,16,17,24,25,28,29,30,31,],[-20,22,-17,-16,-18,-19,-15,22,22,22,-13,-14,]),'RBRACE':([9,10,13,15,16,17,18,19,24,28,29,30,31,32,33,],[-20,-9,-17,-16,-18,-19,-7,27,-15,-12,-11,-13,-14,-10,-8,]),'FLOAT':([6,8,11,14,20,21,22,23,26,],[13,13,13,13,13,13,13,13,13,]),'/':([9,10,13,15,16,17,24,25,28,29,30,31,],[-20,23,-17,-16,-18,-19,-15,23,23,23,-13,-14,]),'INTEGER':([6,8,11,14,20,21,22,23,26,],[15,15,15,15,15,15,15,15,15,]),'Pi':([6,8,11,14,20,21,22,23,26,],[16,16,16,16,16,16,16,16,16,]),'=':([2,],[6,]),',':([9,10,13,15,16,17,18,24,28,29,30,31,32,],[-20,-9,-17,-16,-18,-19,26,-15,-12,-11,-13,-14,-10,]),'$end':([0,1,4,5,7,],[-1,0,-4,-2,-3,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'assignment':([1,],[3,]),'param':([6,8,26,],[12,18,18,]),'paramlist':([8,26,],[19,33,]),'input':([0,],[1,]),'line':([1,],[5,]),'expression':([6,8,11,14,20,21,22,23,26,],[10,10,24,25,28,29,30,31,10,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> input","S'",1,None,None,None),
  ('input -> <empty>','input',0,'p_input','C:\\Users\\HP\\Documents\\ECN\\M1 project\\DrawBot\\read_par.py',186),
  ('input -> input line','input',2,'p_input','C:\\Users\\HP\\Documents\\ECN\\M1 project\\DrawBot\\read_par.py',187),
  ('line -> assignment NEWLINE','line',2,'p_line','C:\\Users\\HP\\Documents\\ECN\\M1 project\\DrawBot\\read_par.py',193),
  ('line -> NEWLINE','line',1,'p_line','C:\\Users\\HP\\Documents\\ECN\\M1 project\\DrawBot\\read_par.py',194),
  ('assignment -> KEYWORD = param','assignment',3,'p_assignment','C:\\Users\\HP\\Documents\\ECN\\M1 project\\DrawBot\\read_par.py',198),
  ('assignment -> KEYWORD = LBRACE paramlist RBRACE','assignment',5,'p_assignment','C:\\Users\\HP\\Documents\\ECN\\M1 project\\DrawBot\\read_par.py',199),
  ('paramlist -> param','paramlist',1,'p_paramlist','C:\\Users\\HP\\Documents\\ECN\\M1 project\\DrawBot\\read_par.py',209),
  ('paramlist -> param , paramlist','paramlist',3,'p_paramlist','C:\\Users\\HP\\Documents\\ECN\\M1 project\\DrawBot\\read_par.py',210),
  ('param -> expression','param',1,'p_param','C:\\Users\\HP\\Documents\\ECN\\M1 project\\DrawBot\\read_par.py',220),
  ('param -> ( expression )','param',3,'p_param','C:\\Users\\HP\\Documents\\ECN\\M1 project\\DrawBot\\read_par.py',221),
  ('expression -> expression + expression','expression',3,'p_expression_binop','C:\\Users\\HP\\Documents\\ECN\\M1 project\\DrawBot\\read_par.py',227),
  ('expression -> expression - expression','expression',3,'p_expression_binop','C:\\Users\\HP\\Documents\\ECN\\M1 project\\DrawBot\\read_par.py',228),
  ('expression -> expression * expression','expression',3,'p_expression_binop','C:\\Users\\HP\\Documents\\ECN\\M1 project\\DrawBot\\read_par.py',229),
  ('expression -> expression / expression','expression',3,'p_expression_binop','C:\\Users\\HP\\Documents\\ECN\\M1 project\\DrawBot\\read_par.py',230),
  ('expression -> - expression','expression',2,'p_expression_uminus','C:\\Users\\HP\\Documents\\ECN\\M1 project\\DrawBot\\read_par.py',244),
  ('expression -> INTEGER','expression',1,'p_expression_term','C:\\Users\\HP\\Documents\\ECN\\M1 project\\DrawBot\\read_par.py',249),
  ('expression -> FLOAT','expression',1,'p_expression_term','C:\\Users\\HP\\Documents\\ECN\\M1 project\\DrawBot\\read_par.py',250),
  ('expression -> Pi','expression',1,'p_expression_term','C:\\Users\\HP\\Documents\\ECN\\M1 project\\DrawBot\\read_par.py',251),
  ('expression -> NAME','expression',1,'p_expression_term','C:\\Users\\HP\\Documents\\ECN\\M1 project\\DrawBot\\read_par.py',252),
  ('expression -> JOINTVAR','expression',1,'p_expression_term','C:\\Users\\HP\\Documents\\ECN\\M1 project\\DrawBot\\read_par.py',253),
]
